chore: Get QuickPick options from fetched matadata
microsoft/vscode-spring-initializr pull request #173
Opened 2021-03-05 08:26 UTC by CsCherrYY

In spring initializr steps, will get QuickPick options from fetched matadata, instead of hard coding the options. see #170.

2021-03-08 07:52 UTC, Eskibear requested changes
'chore' is not proper for this PR. please change it.

2021-03-08 07:52 UTC, Eskibear commented on src/handler/utils.ts
> +                    pickMetadata.metadata.bootVersion = pickBox.selectedItems[0] && pickBox.selectedItems[0].value && pickBox.selectedItems[0].value.id;
can be shortened as `pickBox.selectedItems?.[0]?.value?.id`

2021-03-08 07:52 UTC, Eskibear commented on src/model/ServiceManager.ts
> +        let defaultLable: string;
typo

2021-03-08 08:19 UTC, CsCherrYY commented
> 'chore' is not proper for this PR. please change it.

How about `feat`?

2021-03-08 08:44 UTC, Eskibear commented
rather than a new "feature", it's a "fix" for bug https://github.com/microsoft/vscode-java-pack/issues/547

2021-03-10 04:38 UTC, Eskibear approved these changes

2021-03-10 05:12 UTC, merged